# Generated by Django 5.1.2 on 2024-11-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0004_post_date_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
    ]
